"""vertical_manifest — the M9 lever, and the first domain table

T2 needs somewhere for "everything that differs between verticals" to live as data. Identity and
lifecycle are columns; the cited content is one JSONB body owned by ``ManifestBody``.

Hand-written, not autogenerated, because of the partial unique index below: autogenerate routinely
omits ``postgresql_where``, and that index *is* the invariant this ticket exists to guarantee —
at most one ACTIVE manifest per vertical, enforced by the database rather than only by the service
that happens to be writing today.

Revision ID: 0002_vertical_manifest
Revises: 0001_baseline
Create Date: 2026-09-27

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002_vertical_manifest"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the table, its uniqueness constraints and its lookup index."""
    op.create_table(
        "vertical_manifest",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("vertical", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_by", sa.String(length=128), nullable=True),
        sa.UniqueConstraint("vertical", "version", name="uq_vertical_manifest_vertical_version"),
        # Without this, `status` is any 16 characters. The partial index below keys on the literal
        # 'active', so a row saying 'Active' is exempt from the one-per-vertical invariant *and*
        # invisible to every reader filtering on 'active' — visible to nothing, constrained by
        # nothing. Verified: two such rows for one vertical insert cleanly without this constraint.
        sa.CheckConstraint(
            "status in ('draft', 'active', 'superseded')",
            name="ck_vertical_manifest_status",
        ),
    )
    op.create_index("ix_vertical_manifest_vertical", "vertical_manifest", ["vertical"])
    op.create_index(
        "uq_vertical_manifest_one_active_per_vertical",
        "vertical_manifest",
        ["vertical"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )


def downgrade() -> None:
    """Drop the indexes, then the table."""
    op.drop_index("uq_vertical_manifest_one_active_per_vertical", table_name="vertical_manifest")
    op.drop_index("ix_vertical_manifest_vertical", table_name="vertical_manifest")
    op.drop_table("vertical_manifest")
